APPNAME          = "TcpUdpApTask"

VERSION_MAJOR    = 0
VERSION_MINOR    = 10
VERSION_BUILD    = 0
VERSION_REVISION = 0

VERSION = '%u.%u.%u.%u' % (VERSION_MAJOR, VERSION_MINOR, VERSION_BUILD, VERSION_REVISION)


def build(bld):
  toolchain   = "codesourcery"
  
  comp_prefix = bld.get_name_prefix(toolchain=toolchain)

  sources = ["Sources/TcpUdpApCommands.c",
             "Sources/TcpUdpApTask_Body.c",
             "Sources/TcpUdpApTask_Functions.c",
             "Sources/TcpUdpApTask_Process.c",
             "Sources/TcpUdpApTask_Resources.c",
             "Sources/TcpUdpApTask_TaskInfo.c",
              ]
  
  includes = ["./Includes/",
              ]
  
  defines = ["VERSION_MAJOR    = %u" % VERSION_MAJOR,
             "VERSION_MINOR    = %u" % VERSION_MINOR,
             "RX_COMPILE_CPU_INDEPENDENT",
             ]

  bld.stlib  ( name            = comp_prefix + "rcX_V2.1/" + APPNAME,
               target          = comp_prefix + APPNAME,
               description     = APPNAME,
               displaygroup    = "Libraries",
               platform        = "netx",
               toolchain       = toolchain, 
               source          = sources,
               includes        = includes,
               defines         = defines,
               export_includes = includes,
               use             = [ comp_prefix + "rcX_V2.1/rcx",
                                   comp_prefix + "rcX_V2.1/tcpip",
                                 ]
              )
