APPNAME             = "Application"
VERSION             = "1.0.0.0"
REQUIRED_TOOLCHAINS = ["codesourcery"]


def build(bld):
    
    netx_studio_sources = [
        "Sources/Application.c",
    ]
    
    includes = [
        "Includes",
    ]
    
    public_includes = [
        "Includes",
    ] 
    
    defines = [
    ]
    
    uses = [
    ]
    

    bld.stlib(
        target           = APPNAME,
        name             = "arm-none-eabi/4.5.2/application",
        platform         = "netx",
        toolchain        = "codesourcery",
        description      = "Application",
        source           = netx_studio_sources,
        includes         = includes,
        defines          = defines,
        use              = uses,
        version          = VERSION,
        export_includes  = public_includes,
        displaygroup     = "Application",
        features         = ["libsused"],
    )