def build(bld):
    
    toolchain   = "gccarmemb"
    comp_prefix = bld.get_name_prefix(
        toolchain = toolchain,
        platform  = "netx90")
    
    sources = [
        "Source/main.c",
        "Source/netx90_app_hboot_header.c",
    ]
    
    includes = [
        "Include",
    ]
    
    defines = [ 
        "__NETX90",
        "_NETX_",
        ]
    
    toolchain_prefix = bld.get_name_prefix(
        toolchain = toolchain,
        platform  = "netx90")
    
    uses = [
        toolchain_prefix + "CMSIS",
        toolchain_prefix + "netx_drv"
        ]
    
    bld.program(
        target           = "netx90_app_intram",
        name             = toolchain_prefix + "netx90_app_intram",
        toolchain        = "gccarmemb",
        platform         = "netx90",
        source           = sources,
        includes         = includes,
        defines          = defines,
        use              = uses,
        linkerscript     = ["Linker/netx90_app_intram.ld"],
    )
    
    bld.program(
        target           = "netx90_app_sdram",
        name             = toolchain_prefix + "netx90_app_sdram",
        toolchain        = toolchain,
        platform         = "netx90",
        source           = sources,
        includes         = includes,
        defines          = defines,
        use              = uses,
        linkerscript     = ["Linker/netx90_app_sdram.ld"],
    )
    
    bld.program(
        target           = "netx90_app_iflash",
        name             = toolchain_prefix + "netx90_app_iflash",
        toolchain        = toolchain,
        platform         = "netx90",
        source           = sources,
        includes         = includes,
        defines          = defines,
        use              = uses,
        linkerscript     = ["Linker/netx90_app_iflash.ld"],
    )
    
    
    bld.program(
        target           = "netx90_app_iflash2",
        name             = toolchain_prefix + "netx90_app_iflash2",
        toolchain        = toolchain,
        platform         = "netx90",
        source           = sources,
        includes         = includes,
        defines          = defines,
        use              = uses,
        linkerscript     = ["Linker/netx90_app_iflash.ld"],
    )
    
    bld.generate_netx90_intflash2_image(
        target           = "netx90_app_iflash.nai",
        use              = toolchain_prefix + "netx90_app_iflash"
    )